(******
Invocation of the interface functions of the ERC20 token contract
Copyright (C) 2020  Ning Han, Ximeng Li

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Library General Public License for more details.
******)

theory "CallFuncs"

imports 
  HOL.Option 
  Main "../Syntax" "../Typing" "../SmallStep" MyToken "../utils/Keccak" 
  (*"$ISABELLE_HOME/src/HOL/Word/Word"*)

begin

(*****************************************************************************
                       results for the interface functions                             
 *****************************************************************************)

(*
   function totalSupply() -> supply {                                     
      supply := sload(1)
    }
*)
definition gstk_total_supply_func where
  "gstk_total_supply_func = ((GFrmNormal 
    ([LFrm_B (BEGIN[[s_id] ::= (CALL f_total_supply_id [])]END,
        ls_ex_s0, (get_func_values mytoken_code), None)]) 
    gs1_bfun CKDummy) # [])"
(*
value "multi_step tre0_ex1 gstk_total_supply_func 1"
value "multi_step tre0_ex1 gstk_total_supply_func 2"
value "multi_step tre0_ex1 gstk_total_supply_func 3"
value "multi_step tre0_ex1 gstk_total_supply_func 4"
value "multi_step tre0_ex1 gstk_total_supply_func 5"
value "multi_step tre0_ex1 gstk_total_supply_func 6"
value "multi_step tre0_ex1 gstk_total_supply_func 7"
value "multi_step tre0_ex1 gstk_total_supply_func 8"
value "multi_step tre0_ex1 gstk_total_supply_func 9"
value "multi_step tre0_ex1 gstk_total_supply_func 10"
value "multi_step tre0_ex1 gstk_total_supply_func 11"
value "multi_step tre0_ex1 gstk_total_supply_func 12"
value "multi_step tre0_ex1 gstk_total_supply_func 13"
value "multi_step tre0_ex1 gstk_total_supply_func 14"
value "multi_step tre0_ex1 gstk_total_supply_func 15"
value "multi_step tre0_ex1 gstk_total_supply_func 16"
*)
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_total_supply_func 16) 0x1"

value "check_gs_gas_stp 
        (multi_step tre0_ex1 gstk_total_supply_func 16) (3000000-254)"


(*
    function balanceOf(account) -> bal {                                     
         bal := sload(balanceOffset(account))
    }
*)
definition gstk_balance_of_func where
  "gstk_balance_of_func =  ((GFrmNormal 
    ([LFrm_B (BEGIN[[s_id] ::= (CALL f_balance_of_id [ELit ((NL (0x1234)) :L U256)])]END,
        ls_ex_s0, (get_func_values mytoken_code), None)]) 
    gs1_bfun CKDummy) # [])"
(*
value "multi_step tre0_ex1 gstk_balance_of_func 1"
value "multi_step tre0_ex1 gstk_balance_of_func 2"
value "multi_step tre0_ex1 gstk_balance_of_func 3"
value "multi_step tre0_ex1 gstk_balance_of_func 4"
value "multi_step tre0_ex1 gstk_balance_of_func 5"
value "multi_step tre0_ex1 gstk_balance_of_func 6"
value "multi_step tre0_ex1 gstk_balance_of_func 7"
value "multi_step tre0_ex1 gstk_balance_of_func 8"
value "multi_step tre0_ex1 gstk_balance_of_func 9"
value "multi_step tre0_ex1 gstk_balance_of_func 10"
value "multi_step tre0_ex1 gstk_balance_of_func 11"
value "multi_step tre0_ex1 gstk_balance_of_func 12"
value "multi_step tre0_ex1 gstk_balance_of_func 13"
value "multi_step tre0_ex1 gstk_balance_of_func 14"
value "multi_step tre0_ex1 gstk_balance_of_func 15"
value "multi_step tre0_ex1 gstk_balance_of_func 16"
value "multi_step tre0_ex1 gstk_balance_of_func 17"
value "multi_step tre0_ex1 gstk_balance_of_func 18"
value "multi_step tre0_ex1 gstk_balance_of_func 19"
value "multi_step tre0_ex1 gstk_balance_of_func 20"
value "multi_step tre0_ex1 gstk_balance_of_func 21"
value "multi_step tre0_ex1 gstk_balance_of_func 22"
value "multi_step tre0_ex1 gstk_balance_of_func 23"
value "multi_step tre0_ex1 gstk_balance_of_func 24"
value "multi_step tre0_ex1 gstk_balance_of_func 25"
value "multi_step tre0_ex1 gstk_balance_of_func 26"
value "multi_step tre0_ex1 gstk_balance_of_func 27"
value "multi_step tre0_ex1 gstk_balance_of_func 28"
value "multi_step tre0_ex1 gstk_balance_of_func 29"
value "multi_step tre0_ex1 gstk_balance_of_func 30"
value "multi_step tre0_ex1 gstk_balance_of_func 31"
value "multi_step tre0_ex1 gstk_balance_of_func 32"
value "multi_step tre0_ex1 gstk_balance_of_func 33"
value "multi_step tre0_ex1 gstk_balance_of_func 34"
value "multi_step tre0_ex1 gstk_balance_of_func 35"
value "multi_step tre0_ex1 gstk_balance_of_func 36"
value "multi_step tre0_ex1 gstk_balance_of_func 37"
value "multi_step tre0_ex1 gstk_balance_of_func 38"
value "multi_step tre0_ex1 gstk_balance_of_func 39"
value "multi_step tre0_ex1 gstk_balance_of_func 40"
value "multi_step tre0_ex1 gstk_balance_of_func 42"
value "multi_step tre0_ex1 gstk_balance_of_func 43"
value "multi_step tre0_ex1 gstk_balance_of_func 44"
value "multi_step tre0_ex1 gstk_balance_of_func 45"
value "multi_step tre0_ex1 gstk_balance_of_func 46"
value "multi_step tre0_ex1 gstk_balance_of_func 47"
value "multi_step tre0_ex1 gstk_balance_of_func 48"
value "multi_step tre0_ex1 gstk_balance_of_func 49"
value "multi_step tre0_ex1 gstk_balance_of_func 50"
value "multi_step tre0_ex1 gstk_balance_of_func 51"
value "multi_step tre0_ex1 gstk_balance_of_func 52"
*)
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_balance_of_func 52) 
          (get_balance_offset 0x1234)"

value "check_gs_gas_stp 
        (multi_step tre0_ex1 gstk_balance_of_func 52) (3000000-404)"


(*
  function approve(spender, amount) {                                     
      let sender := caller()  // spender = 0x1234
      sstore(allowOffset(sender, spender), amount)
      log_func(0, sender, spender, amount)
    }
*)
definition gstk_approve_func where
  "gstk_approve_func =  ((GFrmNormal 
    ([LFrm_B (BEGIN[(CALL f_approve_id [ELit ((NL (0x1234)) :L U256), ELit ((NL (66)) :L U256)])]END,
        ls_ex_s0, (get_func_values mytoken_code), None)]) 
    gs1_bfun CKDummy) # [])"
(*
value "multi_step tre0_ex1 gstk_approve_func 1"
value "multi_step tre0_ex1 gstk_approve_func 2"
value "multi_step tre0_ex1 gstk_approve_func 3"
value "multi_step tre0_ex1 gstk_approve_func 4"
value "multi_step tre0_ex1 gstk_approve_func 5"
value "multi_step tre0_ex1 gstk_approve_func 6"
value "multi_step tre0_ex1 gstk_approve_func 7"
value "multi_step tre0_ex1 gstk_approve_func 8"
value "multi_step tre0_ex1 gstk_approve_func 9"
value "multi_step tre0_ex1 gstk_approve_func 10"
value "multi_step tre0_ex1 gstk_approve_func 11"
value "multi_step tre0_ex1 gstk_approve_func 12"
value "multi_step tre0_ex1 gstk_approve_func 13"
value "multi_step tre0_ex1 gstk_approve_func 14"
value "multi_step tre0_ex1 gstk_approve_func 15"
value "multi_step tre0_ex1 gstk_approve_func 16"
value "multi_step tre0_ex1 gstk_approve_func 17"
value "multi_step tre0_ex1 gstk_approve_func 18"
value "multi_step tre0_ex1 gstk_approve_func 19"
value "multi_step tre0_ex1 gstk_approve_func 20"
value "multi_step tre0_ex1 gstk_approve_func 21"
value "multi_step tre0_ex1 gstk_approve_func 22"
value "multi_step tre0_ex1 gstk_approve_func 23"
value "multi_step tre0_ex1 gstk_approve_func 24"
value "multi_step tre0_ex1 gstk_approve_func 25"
value "multi_step tre0_ex1 gstk_approve_func 26"
value "multi_step tre0_ex1 gstk_approve_func 27"
value "multi_step tre0_ex1 gstk_approve_func 28"
value "multi_step tre0_ex1 gstk_approve_func 29"
value "multi_step tre0_ex1 gstk_approve_func 30"
value "multi_step tre0_ex1 gstk_approve_func 31"
value "multi_step tre0_ex1 gstk_approve_func 32"
value "multi_step tre0_ex1 gstk_approve_func 33"
value "multi_step tre0_ex1 gstk_approve_func 34"
value "multi_step tre0_ex1 gstk_approve_func 35"
value "multi_step tre0_ex1 gstk_approve_func 36"
value "multi_step tre0_ex1 gstk_approve_func 37"
value "multi_step tre0_ex1 gstk_approve_func 38"
value "multi_step tre0_ex1 gstk_approve_func 39"
value "multi_step tre0_ex1 gstk_approve_func 40"
value "multi_step tre0_ex1 gstk_approve_func 41"
value "multi_step tre0_ex1 gstk_approve_func 42"
value "multi_step tre0_ex1 gstk_approve_func 43"
value "multi_step tre0_ex1 gstk_approve_func 44"
value "multi_step tre0_ex1 gstk_approve_func 45"
value "multi_step tre0_ex1 gstk_approve_func 46"
value "multi_step tre0_ex1 gstk_approve_func 47"
value "multi_step tre0_ex1 gstk_approve_func 48"
value "multi_step tre0_ex1 gstk_approve_func 49"
value "multi_step tre0_ex1 gstk_approve_func 50"
value "multi_step tre0_ex1 gstk_approve_func 51"
value "multi_step tre0_ex1 gstk_approve_func 52"
value "multi_step tre0_ex1 gstk_approve_func 53"
value "multi_step tre0_ex1 gstk_approve_func 54"     
value "multi_step tre0_ex1 gstk_approve_func 55"
value "multi_step tre0_ex1 gstk_approve_func 56"
value "multi_step tre0_ex1 gstk_approve_func 57"
value "multi_step tre0_ex1 gstk_approve_func 58"
value "multi_step tre0_ex1 gstk_approve_func 59"
value "multi_step tre0_ex1 gstk_approve_func 60"
value "multi_step tre0_ex1 gstk_approve_func 61"
value "multi_step tre0_ex1 gstk_approve_func 62"
value "multi_step tre0_ex1 gstk_approve_func 63"
value "multi_step tre0_ex1 gstk_approve_func 64"
value "multi_step tre0_ex1 gstk_approve_func 65"
value "multi_step tre0_ex1 gstk_approve_func 66"
value "multi_step tre0_ex1 gstk_approve_func 67"
value "multi_step tre0_ex1 gstk_approve_func 68"
value "multi_step tre0_ex1 gstk_approve_func 69"
value "multi_step tre0_ex1 gstk_approve_func 70"
value "multi_step tre0_ex1 gstk_approve_func 71"
value "multi_step tre0_ex1 gstk_approve_func 72"
value "multi_step tre0_ex1 gstk_approve_func 73"
value "multi_step tre0_ex1 gstk_approve_func 74"
value "multi_step tre0_ex1 gstk_approve_func 75"
value "multi_step tre0_ex1 gstk_approve_func 76"
value "multi_step tre0_ex1 gstk_approve_func 77"
value "multi_step tre0_ex1 gstk_approve_func 78"
value "multi_step tre0_ex1 gstk_approve_func 80"
value "multi_step tre0_ex1 gstk_approve_func 82"
value "multi_step tre0_ex1 gstk_approve_func 83"
value "multi_step tre0_ex1 gstk_approve_func 84"
value "multi_step tre0_ex1 gstk_approve_func 85"
value "multi_step tre0_ex1 gstk_approve_func 86"
value "multi_step tre0_ex1 gstk_approve_func 87"
value "multi_step tre0_ex1 gstk_approve_func 88"
value "multi_step tre0_ex1 gstk_approve_func 89"
value "multi_step tre0_ex1 gstk_approve_func 90"
value "multi_step tre0_ex1 gstk_approve_func 91"
value "multi_step tre0_ex1 gstk_approve_func 92"
value "multi_step tre0_ex1 gstk_approve_func 93"
value "multi_step tre0_ex1 gstk_approve_func 94"
value "multi_step tre0_ex1 gstk_approve_func 95"
value "multi_step tre0_ex1 gstk_approve_func 96"
value "multi_step tre0_ex1 gstk_approve_func 97"
value "multi_step tre0_ex1 gstk_approve_func 98"
value "multi_step tre0_ex1 gstk_approve_func 99"
value "multi_step tre0_ex1 gstk_approve_func 100"
value "multi_step tre0_ex1 gstk_approve_func 101"
value "multi_step tre0_ex1 gstk_approve_func 102"
value "multi_step tre0_ex1 gstk_approve_func 103"
*)
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_approve_func 5) 
          (get_allowance_offset (saddr_of gs1_bfun) 0x1234)"

value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_approve_func 103) 
          (get_allowance_offset (saddr_of gs1_bfun) 0x1234)"

value "check_gs_gas_stp 
        (multi_step tre0_ex1 gstk_approve_func 103) (3000000-6768)"


(*
    function allowance_func(from, by) -> amount {         
      amount := sload(allowOffset(from, by))
    }
*)
definition gstk_allowance_func where
  "gstk_allowance_func = ((GFrmNormal 
    ([LFrm_B (BEGIN[[s_id] ::= (CALL f_allowance_id [ELit ((NL (0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)) :L U256), 
                          ELit ((NL (0x1234)) :L U256)])]END,
        ls_ex_s0, (get_func_values mytoken_code), None)]) gs1_bfun CKDummy) # [])"
(*
value "multi_step tre0_ex1 gstk_allowance_func 1" 
value "multi_step tre0_ex1 gstk_allowance_func 2"
value "multi_step tre0_ex1 gstk_allowance_func 3"
value "multi_step tre0_ex1 gstk_allowance_func 4"
value "multi_step tre0_ex1 gstk_allowance_func 5"
value "multi_step tre0_ex1 gstk_allowance_func 6"
value "multi_step tre0_ex1 gstk_allowance_func 7"
value "multi_step tre0_ex1 gstk_allowance_func 8"
value "multi_step tre0_ex1 gstk_allowance_func 9"
value "multi_step tre0_ex1 gstk_allowance_func 10"
value "multi_step tre0_ex1 gstk_allowance_func 11"
value "multi_step tre0_ex1 gstk_allowance_func 12"
value "multi_step tre0_ex1 gstk_allowance_func 13"
value "multi_step tre0_ex1 gstk_allowance_func 14"
value "multi_step tre0_ex1 gstk_allowance_func 15"
value "multi_step tre0_ex1 gstk_allowance_func 16"
value "multi_step tre0_ex1 gstk_allowance_func 17"
value "multi_step tre0_ex1 gstk_allowance_func 18"
value "multi_step tre0_ex1 gstk_allowance_func 19"
value "multi_step tre0_ex1 gstk_allowance_func 20"
value "multi_step tre0_ex1 gstk_allowance_func 21"
value "multi_step tre0_ex1 gstk_allowance_func 22"
value "multi_step tre0_ex1 gstk_allowance_func 23"
value "multi_step tre0_ex1 gstk_allowance_func 24"
value "multi_step tre0_ex1 gstk_allowance_func 25"
value "multi_step tre0_ex1 gstk_allowance_func 26"
value "multi_step tre0_ex1 gstk_allowance_func 27"
value "multi_step tre0_ex1 gstk_allowance_func 28"
value "multi_step tre0_ex1 gstk_allowance_func 29"
value "multi_step tre0_ex1 gstk_allowance_func 30"
value "multi_step tre0_ex1 gstk_allowance_func 31"
value "multi_step tre0_ex1 gstk_allowance_func 32"
value "multi_step tre0_ex1 gstk_allowance_func 33"
value "multi_step tre0_ex1 gstk_allowance_func 34"
value "multi_step tre0_ex1 gstk_allowance_func 35"
value "multi_step tre0_ex1 gstk_allowance_func 36"
value "multi_step tre0_ex1 gstk_allowance_func 37"
value "multi_step tre0_ex1 gstk_allowance_func 38"
value "multi_step tre0_ex1 gstk_allowance_func 39"
value "multi_step tre0_ex1 gstk_allowance_func 40"
value "multi_step tre0_ex1 gstk_allowance_func 41"
value "multi_step tre0_ex1 gstk_allowance_func 42"
value "multi_step tre0_ex1 gstk_allowance_func 43"
value "multi_step tre0_ex1 gstk_allowance_func 44"
value "multi_step tre0_ex1 gstk_allowance_func 45"
value "multi_step tre0_ex1 gstk_allowance_func 48"
value "multi_step tre0_ex1 gstk_allowance_func 49"
value "multi_step tre0_ex1 gstk_allowance_func 50"
value "multi_step tre0_ex1 gstk_allowance_func 51"
value "multi_step tre0_ex1 gstk_allowance_func 52"
value "multi_step tre0_ex1 gstk_allowance_func 56"
value "multi_step tre0_ex1 gstk_allowance_func 57"
value "multi_step tre0_ex1 gstk_allowance_func 58"
value "multi_step tre0_ex1 gstk_allowance_func 59"
value "multi_step tre0_ex1 gstk_allowance_func 60"
value "multi_step tre0_ex1 gstk_allowance_func 64"
value "multi_step tre0_ex1 gstk_allowance_func 65"
value "multi_step tre0_ex1 gstk_allowance_func 66"
value "multi_step tre0_ex1 gstk_allowance_func 67"
value "multi_step tre0_ex1 gstk_allowance_func 68"
value "multi_step tre0_ex1 gstk_allowance_func 69"
value "multi_step tre0_ex1 gstk_allowance_func 70"
value "multi_step tre0_ex1 gstk_allowance_func 71"
value "multi_step tre0_ex1 gstk_allowance_func 72"
value "multi_step tre0_ex1 gstk_allowance_func 73"
value "multi_step tre0_ex1 gstk_allowance_func 74"
value "multi_step tre0_ex1 gstk_allowance_func 75"
value "multi_step tre0_ex1 gstk_allowance_func 76"
value "multi_step tre0_ex1 gstk_allowance_func 77"
*)
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_allowance_func 77) 
          (get_allowance_offset (saddr_of gs1_bfun) 0x1234)"

value "check_gs_gas_stp 
        (multi_step tre0_ex1 gstk_allowance_func 77) (3000000-513)"


(*
  function transfer_func(to, amount) {
    deductFromBalance(caller(), amount)
    addToBalance(to, amount)
    log_func(1, caller(), to, amount)
  }
*)
definition gstk_transfer_func where
  "gstk_transfer_func = ((GFrmNormal 
    ([LFrm_B (BEGIN[(CALL f_transfer_id [ELit ((NL (0x1234)) :L U256),
                                                            ELit ((NL 10) :L U256)])]END,
        ls_ex_s0, (get_func_values mytoken_code), None)]) 
    gs1_bfun CKDummy) # [])"
(*               
value "multi_step tre0_ex1 gstk_transfer_func 1"
value "multi_step tre0_ex1 gstk_transfer_func 2"
value "multi_step tre0_ex1 gstk_transfer_func 3"
value "multi_step tre0_ex1 gstk_transfer_func 4"
value "multi_step tre0_ex1 gstk_transfer_func 5"
value "multi_step tre0_ex1 gstk_transfer_func 6"
value "multi_step tre0_ex1 gstk_transfer_func 7"
value "multi_step tre0_ex1 gstk_transfer_func 8"
value "multi_step tre0_ex1 gstk_transfer_func 9"
value "multi_step tre0_ex1 gstk_transfer_func 10"
value "multi_step tre0_ex1 gstk_transfer_func 11"
value "multi_step tre0_ex1 gstk_transfer_func 12"
value "multi_step tre0_ex1 gstk_transfer_func 13"
value "multi_step tre0_ex1 gstk_transfer_func 14"
value "multi_step tre0_ex1 gstk_transfer_func 15"
value "multi_step tre0_ex1 gstk_transfer_func 16"
value "multi_step tre0_ex1 gstk_transfer_func 17"
value "multi_step tre0_ex1 gstk_transfer_func 18"
value "multi_step tre0_ex1 gstk_transfer_func 19"
value "multi_step tre0_ex1 gstk_transfer_func 20"
value "multi_step tre0_ex1 gstk_transfer_func 21"
value "multi_step tre0_ex1 gstk_transfer_func 22"
value "multi_step tre0_ex1 gstk_transfer_func 23"
value "multi_step tre0_ex1 gstk_transfer_func 24"   
value "multi_step tre0_ex1 gstk_transfer_func 25"
value "multi_step tre0_ex1 gstk_transfer_func 26"
value "multi_step tre0_ex1 gstk_transfer_func 27"
value "multi_step tre0_ex1 gstk_transfer_func 28"
value "multi_step tre0_ex1 gstk_transfer_func 29"
value "multi_step tre0_ex1 gstk_transfer_func 30"
value "multi_step tre0_ex1 gstk_transfer_func 31"
value "multi_step tre0_ex1 gstk_transfer_func 32"
value "multi_step tre0_ex1 gstk_transfer_func 33"
value "multi_step tre0_ex1 gstk_transfer_func 34"
value "multi_step tre0_ex1 gstk_transfer_func 35"
value "multi_step tre0_ex1 gstk_transfer_func 36"
value "multi_step tre0_ex1 gstk_transfer_func 37"
value "multi_step tre0_ex1 gstk_transfer_func 38"
value "multi_step tre0_ex1 gstk_transfer_func 39"
value "multi_step tre0_ex1 gstk_transfer_func 40"
value "multi_step tre0_ex1 gstk_transfer_func 41"
value "multi_step tre0_ex1 gstk_transfer_func 42"
value "multi_step tre0_ex1 gstk_transfer_func 43"
value "multi_step tre0_ex1 gstk_transfer_func 44"
value "multi_step tre0_ex1 gstk_transfer_func 45"
value "multi_step tre0_ex1 gstk_transfer_func 46"
value "multi_step tre0_ex1 gstk_transfer_func 47"
value "multi_step tre0_ex1 gstk_transfer_func 48"
value "multi_step tre0_ex1 gstk_transfer_func 49"
value "multi_step tre0_ex1 gstk_transfer_func 50"
value "multi_step tre0_ex1 gstk_transfer_func 51"
value "multi_step tre0_ex1 gstk_transfer_func 52"
value "multi_step tre0_ex1 gstk_transfer_func 53"
value "multi_step tre0_ex1 gstk_transfer_func 54"
value "multi_step tre0_ex1 gstk_transfer_func 55"
value "multi_step tre0_ex1 gstk_transfer_func 56"
value "multi_step tre0_ex1 gstk_transfer_func 57"
value "multi_step tre0_ex1 gstk_transfer_func 58"
value "multi_step tre0_ex1 gstk_transfer_func 59"
value "multi_step tre0_ex1 gstk_transfer_func 60"
value "multi_step tre0_ex1 gstk_transfer_func 61"
value "multi_step tre0_ex1 gstk_transfer_func 62"
value "multi_step tre0_ex1 gstk_transfer_func 63"
value "multi_step tre0_ex1 gstk_transfer_func 64"
value "multi_step tre0_ex1 gstk_transfer_func 65"
value "multi_step tre0_ex1 gstk_transfer_func 66"
value "multi_step tre0_ex1 gstk_transfer_func 67"
value "multi_step tre0_ex1 gstk_transfer_func 68"
value "multi_step tre0_ex1 gstk_transfer_func 69"
value "multi_step tre0_ex1 gstk_transfer_func 70"
value "multi_step tre0_ex1 gstk_transfer_func 71"
value "multi_step tre0_ex1 gstk_transfer_func 72"
value "multi_step tre0_ex1 gstk_transfer_func 73"
value "multi_step tre0_ex1 gstk_transfer_func 74"
value "multi_step tre0_ex1 gstk_transfer_func 75"
value "multi_step tre0_ex1 gstk_transfer_func 76"
value "multi_step tre0_ex1 gstk_transfer_func 77"
value "multi_step tre0_ex1 gstk_transfer_func 78"
value "multi_step tre0_ex1 gstk_transfer_func 79"
value "multi_step tre0_ex1 gstk_transfer_func 80"
value "multi_step tre0_ex1 gstk_transfer_func 81"
value "multi_step tre0_ex1 gstk_transfer_func 82"
value "multi_step tre0_ex1 gstk_transfer_func 83"
value "multi_step tre0_ex1 gstk_transfer_func 84"
value "multi_step tre0_ex1 gstk_transfer_func 85"
value "multi_step tre0_ex1 gstk_transfer_func 86"
value "multi_step tre0_ex1 gstk_transfer_func 87"
value "multi_step tre0_ex1 gstk_transfer_func 88"
value "multi_step tre0_ex1 gstk_transfer_func 89"
value "multi_step tre0_ex1 gstk_transfer_func 90"
value "multi_step tre0_ex1 gstk_transfer_func 91"
value "multi_step tre0_ex1 gstk_transfer_func 92"
value "multi_step tre0_ex1 gstk_transfer_func 93"
value "multi_step tre0_ex1 gstk_transfer_func 94"
value "multi_step tre0_ex1 gstk_transfer_func 95"
value "multi_step tre0_ex1 gstk_transfer_func 96"
value "multi_step tre0_ex1 gstk_transfer_func 97"
value "multi_step tre0_ex1 gstk_transfer_func 98"
value "multi_step tre0_ex1 gstk_transfer_func 99"
value "multi_step tre0_ex1 gstk_transfer_func 100"
value "multi_step tre0_ex1 gstk_transfer_func 101"
value "multi_step tre0_ex1 gstk_transfer_func 102"
value "multi_step tre0_ex1 gstk_transfer_func 103"
value "multi_step tre0_ex1 gstk_transfer_func 104"
value "multi_step tre0_ex1 gstk_transfer_func 105"
value "multi_step tre0_ex1 gstk_transfer_func 106"
value "multi_step tre0_ex1 gstk_transfer_func 107"
value "multi_step tre0_ex1 gstk_transfer_func 108"
value "multi_step tre0_ex1 gstk_transfer_func 109"
value "multi_step tre0_ex1 gstk_transfer_func 110"
value "multi_step tre0_ex1 gstk_transfer_func 111"
value "multi_step tre0_ex1 gstk_transfer_func 112"
value "multi_step tre0_ex1 gstk_transfer_func 113"
value "multi_step tre0_ex1 gstk_transfer_func 114"
value "multi_step tre0_ex1 gstk_transfer_func 115"
value "multi_step tre0_ex1 gstk_transfer_func 116"
value "multi_step tre0_ex1 gstk_transfer_func 117"
value "multi_step tre0_ex1 gstk_transfer_func 118"
value "multi_step tre0_ex1 gstk_transfer_func 119"
value "multi_step tre0_ex1 gstk_transfer_func 120"
value "multi_step tre0_ex1 gstk_transfer_func 121"
value "multi_step tre0_ex1 gstk_transfer_func 125"
value "multi_step tre0_ex1 gstk_transfer_func 126"
value "multi_step tre0_ex1 gstk_transfer_func 127"
value "multi_step tre0_ex1 gstk_transfer_func 128"
value "multi_step tre0_ex1 gstk_transfer_func 129"
value "multi_step tre0_ex1 gstk_transfer_func 130"
value "multi_step tre0_ex1 gstk_transfer_func 131"
value "multi_step tre0_ex1 gstk_transfer_func 132"
value "multi_step tre0_ex1 gstk_transfer_func 133"
value "multi_step tre0_ex1 gstk_transfer_func 134"
value "multi_step tre0_ex1 gstk_transfer_func 135"
value "multi_step tre0_ex1 gstk_transfer_func 136"
value "multi_step tre0_ex1 gstk_transfer_func 137"
value "multi_step tre0_ex1 gstk_transfer_func 138"
value "multi_step tre0_ex1 gstk_transfer_func 139"
value "multi_step tre0_ex1 gstk_transfer_func 140"
value "multi_step tre0_ex1 gstk_transfer_func 141"
value "multi_step tre0_ex1 gstk_transfer_func 142"
value "multi_step tre0_ex1 gstk_transfer_func 143"
value "multi_step tre0_ex1 gstk_transfer_func 144"
value "multi_step tre0_ex1 gstk_transfer_func 145"
value "multi_step tre0_ex1 gstk_transfer_func 146"
value "multi_step tre0_ex1 gstk_transfer_func 147"
value "multi_step tre0_ex1 gstk_transfer_func 148"
value "multi_step tre0_ex1 gstk_transfer_func 149"
value "multi_step tre0_ex1 gstk_transfer_func 152"
value "multi_step tre0_ex1 gstk_transfer_func 153"
value "multi_step tre0_ex1 gstk_transfer_func 154"
value "multi_step tre0_ex1 gstk_transfer_func 155"
value "multi_step tre0_ex1 gstk_transfer_func 156"
value "multi_step tre0_ex1 gstk_transfer_func 157"
value "multi_step tre0_ex1 gstk_transfer_func 158"
value "multi_step tre0_ex1 gstk_transfer_func 159"
value "multi_step tre0_ex1 gstk_transfer_func 160"
value "multi_step tre0_ex1 gstk_transfer_func 161"
value "multi_step tre0_ex1 gstk_transfer_func 162"
value "multi_step tre0_ex1 gstk_transfer_func 163"
value "multi_step tre0_ex1 gstk_transfer_func 164"
value "multi_step tre0_ex1 gstk_transfer_func 165"
value "multi_step tre0_ex1 gstk_transfer_func 166"
value "multi_step tre0_ex1 gstk_transfer_func 167"
value "multi_step tre0_ex1 gstk_transfer_func 168"
value "multi_step tre0_ex1 gstk_transfer_func 169"
value "multi_step tre0_ex1 gstk_transfer_func 170"
value "multi_step tre0_ex1 gstk_transfer_func 171"
value "multi_step tre0_ex1 gstk_transfer_func 172"
value "multi_step tre0_ex1 gstk_transfer_func 173"
value "multi_step tre0_ex1 gstk_transfer_func 174"
value "multi_step tre0_ex1 gstk_transfer_func 175"
value "multi_step tre0_ex1 gstk_transfer_func 176"
value "multi_step tre0_ex1 gstk_transfer_func 177"
value "multi_step tre0_ex1 gstk_transfer_func 178"
value "multi_step tre0_ex1 gstk_transfer_func 179"
value "multi_step tre0_ex1 gstk_transfer_func 180"
value "multi_step tre0_ex1 gstk_transfer_func 181"
value "multi_step tre0_ex1 gstk_transfer_func 182"
value "multi_step tre0_ex1 gstk_transfer_func 183"
value "multi_step tre0_ex1 gstk_transfer_func 184"
value "multi_step tre0_ex1 gstk_transfer_func 185"
*)
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_func 66) 
          (get_balance_offset 0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_func 67) 
          (get_balance_offset 0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_func 146) 
          (get_balance_offset 0x1234)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_func 147) 
          (get_balance_offset 0x1234)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_func 185) 
          (get_balance_offset 0x1234)"

value "check_gs_gas_stp 
        (multi_step tre0_ex1 gstk_transfer_func 185) (3000000-12410)"


(*
  function transferFrom(from, to, amount) {
    let sender := caller()
    let allowance := allowance_func(from, sender)
    if lt(sub(exp(2, 256), 1), allowance) { revert(0, 0) }
    if lt(allowance, amount) { revert(0, 0) }   
    deductFromBalance(from, amount)
    addToBalance(to, amount)
    sstore(allowOffset(from, sender), sub(allowance, amount))
    log_func(2, from, to, amount)
  }        	  
*)
definition gstk_transfer_from_func where
  "gstk_transfer_from_func = ((GFrmNormal 
    ([LFrm_B (BEGIN[(CALL f_transfer_from_id [ELit ((NL (0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)) :L U256),
                              ELit ((NL (0x1234)) :L U256),
                              ELit ((NL 10) :L U256)])]END,
        ls_ex_s0, (get_func_values mytoken_code), None)]) 
    gs1_bfun CKDummy) # [])"
(*
value "multi_step tre0_ex1 gstk_transfer_from_func 1"
value "multi_step tre0_ex1 gstk_transfer_from_func 2"
value "multi_step tre0_ex1 gstk_transfer_from_func 3"
value "multi_step tre0_ex1 gstk_transfer_from_func 4"
value "multi_step tre0_ex1 gstk_transfer_from_func 5"
value "multi_step tre0_ex1 gstk_transfer_from_func 6"
value "multi_step tre0_ex1 gstk_transfer_from_func 7"
value "multi_step tre0_ex1 gstk_transfer_from_func 8"
value "multi_step tre0_ex1 gstk_transfer_from_func 9"
value "multi_step tre0_ex1 gstk_transfer_from_func 10"
value "multi_step tre0_ex1 gstk_transfer_from_func 11"
value "multi_step tre0_ex1 gstk_transfer_from_func 12"
value "multi_step tre0_ex1 gstk_transfer_from_func 13"
value "multi_step tre0_ex1 gstk_transfer_from_func 14"
value "multi_step tre0_ex1 gstk_transfer_from_func 15"
value "multi_step tre0_ex1 gstk_transfer_from_func 16"
value "multi_step tre0_ex1 gstk_transfer_from_func 17"
value "multi_step tre0_ex1 gstk_transfer_from_func 18"
value "multi_step tre0_ex1 gstk_transfer_from_func 19"
value "multi_step tre0_ex1 gstk_transfer_from_func 20"
value "multi_step tre0_ex1 gstk_transfer_from_func 21"
value "multi_step tre0_ex1 gstk_transfer_from_func 22"
value "multi_step tre0_ex1 gstk_transfer_from_func 23"
value "multi_step tre0_ex1 gstk_transfer_from_func 24"
value "multi_step tre0_ex1 gstk_transfer_from_func 25"
value "multi_step tre0_ex1 gstk_transfer_from_func 26"
value "multi_step tre0_ex1 gstk_transfer_from_func 27"
value "multi_step tre0_ex1 gstk_transfer_from_func 28"
value "multi_step tre0_ex1 gstk_transfer_from_func 29"
value "multi_step tre0_ex1 gstk_transfer_from_func 30"
value "multi_step tre0_ex1 gstk_transfer_from_func 31"
value "multi_step tre0_ex1 gstk_transfer_from_func 32"
value "multi_step tre0_ex1 gstk_transfer_from_func 33"
value "multi_step tre0_ex1 gstk_transfer_from_func 34"
value "multi_step tre0_ex1 gstk_transfer_from_func 35"
value "multi_step tre0_ex1 gstk_transfer_from_func 36"
value "multi_step tre0_ex1 gstk_transfer_from_func 37"
value "multi_step tre0_ex1 gstk_transfer_from_func 38"
value "multi_step tre0_ex1 gstk_transfer_from_func 39"
value "multi_step tre0_ex1 gstk_transfer_from_func 40"
value "multi_step tre0_ex1 gstk_transfer_from_func 41"
value "multi_step tre0_ex1 gstk_transfer_from_func 42"
value "multi_step tre0_ex1 gstk_transfer_from_func 43"
value "multi_step tre0_ex1 gstk_transfer_from_func 44"
value "multi_step tre0_ex1 gstk_transfer_from_func 45"
value "multi_step tre0_ex1 gstk_transfer_from_func 46"
value "multi_step tre0_ex1 gstk_transfer_from_func 47"
value "multi_step tre0_ex1 gstk_transfer_from_func 48"
value "multi_step tre0_ex1 gstk_transfer_from_func 49"
value "multi_step tre0_ex1 gstk_transfer_from_func 50"
value "multi_step tre0_ex1 gstk_transfer_from_func 51"
value "multi_step tre0_ex1 gstk_transfer_from_func 53"
value "multi_step tre0_ex1 gstk_transfer_from_func 55"
value "multi_step tre0_ex1 gstk_transfer_from_func 56"
value "multi_step tre0_ex1 gstk_transfer_from_func 57"
value "multi_step tre0_ex1 gstk_transfer_from_func 58"
value "multi_step tre0_ex1 gstk_transfer_from_func 59"
value "multi_step tre0_ex1 gstk_transfer_from_func 60"
value "multi_step tre0_ex1 gstk_transfer_from_func 62"
value "multi_step tre0_ex1 gstk_transfer_from_func 64"
value "multi_step tre0_ex1 gstk_transfer_from_func 65"
value "multi_step tre0_ex1 gstk_transfer_from_func 66"
value "multi_step tre0_ex1 gstk_transfer_from_func 67"
value "multi_step tre0_ex1 gstk_transfer_from_func 68"
value "multi_step tre0_ex1 gstk_transfer_from_func 69"
value "multi_step tre0_ex1 gstk_transfer_from_func 70"
value "multi_step tre0_ex1 gstk_transfer_from_func 71"
value "multi_step tre0_ex1 gstk_transfer_from_func 72"
value "multi_step tre0_ex1 gstk_transfer_from_func 73"
value "multi_step tre0_ex1 gstk_transfer_from_func 74"
value "multi_step tre0_ex1 gstk_transfer_from_func 75"
value "multi_step tre0_ex1 gstk_transfer_from_func 76"
value "multi_step tre0_ex1 gstk_transfer_from_func 78"
value "multi_step tre0_ex1 gstk_transfer_from_func 79"
value "multi_step tre0_ex1 gstk_transfer_from_func 80"
value "multi_step tre0_ex1 gstk_transfer_from_func 84"
value "multi_step tre0_ex1 gstk_transfer_from_func 85"
value "multi_step tre0_ex1 gstk_transfer_from_func 86"
value "multi_step tre0_ex1 gstk_transfer_from_func 87"
value "multi_step tre0_ex1 gstk_transfer_from_func 88"
value "multi_step tre0_ex1 gstk_transfer_from_func 89"
value "multi_step tre0_ex1 gstk_transfer_from_func 90"
value "multi_step tre0_ex1 gstk_transfer_from_func 91"
value "multi_step tre0_ex1 gstk_transfer_from_func 92"
value "multi_step tre0_ex1 gstk_transfer_from_func 93"
value "multi_step tre0_ex1 gstk_transfer_from_func 94"
value "multi_step tre0_ex1 gstk_transfer_from_func 95"
value "multi_step tre0_ex1 gstk_transfer_from_func 96"
value "multi_step tre0_ex1 gstk_transfer_from_func 99"
value "multi_step tre0_ex1 gstk_transfer_from_func 100"
value "multi_step tre0_ex1 gstk_transfer_from_func 101"
value "multi_step tre0_ex1 gstk_transfer_from_func 102"
value "multi_step tre0_ex1 gstk_transfer_from_func 103"
value "multi_step tre0_ex1 gstk_transfer_from_func 104"
value "multi_step tre0_ex1 gstk_transfer_from_func 105"
value "multi_step tre0_ex1 gstk_transfer_from_func 106"
value "multi_step tre0_ex1 gstk_transfer_from_func 107"
value "multi_step tre0_ex1 gstk_transfer_from_func 108"
value "multi_step tre0_ex1 gstk_transfer_from_func 109"
value "multi_step tre0_ex1 gstk_transfer_from_func 110"
value "multi_step tre0_ex1 gstk_transfer_from_func 111"
value "multi_step tre0_ex1 gstk_transfer_from_func 112"
value "multi_step tre0_ex1 gstk_transfer_from_func 113"
value "multi_step tre0_ex1 gstk_transfer_from_func 114"
value "multi_step tre0_ex1 gstk_transfer_from_func 115"
value "multi_step tre0_ex1 gstk_transfer_from_func 116"
value "multi_step tre0_ex1 gstk_transfer_from_func 117"
value "multi_step tre0_ex1 gstk_transfer_from_func 118"
value "multi_step tre0_ex1 gstk_transfer_from_func 119"
value "multi_step tre0_ex1 gstk_transfer_from_func 120"
value "multi_step tre0_ex1 gstk_transfer_from_func 121"
value "multi_step tre0_ex1 gstk_transfer_from_func 122"
value "multi_step tre0_ex1 gstk_transfer_from_func 123"
value "multi_step tre0_ex1 gstk_transfer_from_func 124"
value "multi_step tre0_ex1 gstk_transfer_from_func 125"
value "multi_step tre0_ex1 gstk_transfer_from_func 126"
value "multi_step tre0_ex1 gstk_transfer_from_func 127"
value "multi_step tre0_ex1 gstk_transfer_from_func 128"
value "multi_step tre0_ex1 gstk_transfer_from_func 129"
value "multi_step tre0_ex1 gstk_transfer_from_func 130"
value "multi_step tre0_ex1 gstk_transfer_from_func 131"
value "multi_step tre0_ex1 gstk_transfer_from_func 132"
value "multi_step tre0_ex1 gstk_transfer_from_func 133"
value "multi_step tre0_ex1 gstk_transfer_from_func 134"
value "multi_step tre0_ex1 gstk_transfer_from_func 135"
value "multi_step tre0_ex1 gstk_transfer_from_func 136"
value "multi_step tre0_ex1 gstk_transfer_from_func 137"
value "multi_step tre0_ex1 gstk_transfer_from_func 138"
value "multi_step tre0_ex1 gstk_transfer_from_func 139"
value "multi_step tre0_ex1 gstk_transfer_from_func 140"
value "multi_step tre0_ex1 gstk_transfer_from_func 141"
value "multi_step tre0_ex1 gstk_transfer_from_func 142"
value "multi_step tre0_ex1 gstk_transfer_from_func 148"
value "multi_step tre0_ex1 gstk_transfer_from_func 149"
value "multi_step tre0_ex1 gstk_transfer_from_func 150"
value "multi_step tre0_ex1 gstk_transfer_from_func 151"
value "multi_step tre0_ex1 gstk_transfer_from_func 152"
value "multi_step tre0_ex1 gstk_transfer_from_func 153"
value "multi_step tre0_ex1 gstk_transfer_from_func 154"
value "multi_step tre0_ex1 gstk_transfer_from_func 155"
value "multi_step tre0_ex1 gstk_transfer_from_func 156"
value "multi_step tre0_ex1 gstk_transfer_from_func 157"
value "multi_step tre0_ex1 gstk_transfer_from_func 158"
value "multi_step tre0_ex1 gstk_transfer_from_func 159"
value "multi_step tre0_ex1 gstk_transfer_from_func 160"
value "multi_step tre0_ex1 gstk_transfer_from_func 161"
value "multi_step tre0_ex1 gstk_transfer_from_func 162"
value "multi_step tre0_ex1 gstk_transfer_from_func 163"
value "multi_step tre0_ex1 gstk_transfer_from_func 164"
value "multi_step tre0_ex1 gstk_transfer_from_func 165"
value "multi_step tre0_ex1 gstk_transfer_from_func 166"
value "multi_step tre0_ex1 gstk_transfer_from_func 167"
value "multi_step tre0_ex1 gstk_transfer_from_func 168"
value "multi_step tre0_ex1 gstk_transfer_from_func 169"
value "multi_step tre0_ex1 gstk_transfer_from_func 170"
value "multi_step tre0_ex1 gstk_transfer_from_func 171"
value "multi_step tre0_ex1 gstk_transfer_from_func 172"
value "multi_step tre0_ex1 gstk_transfer_from_func 173"
value "multi_step tre0_ex1 gstk_transfer_from_func 174"
value "multi_step tre0_ex1 gstk_transfer_from_func 175"
value "multi_step tre0_ex1 gstk_transfer_from_func 176"
value "multi_step tre0_ex1 gstk_transfer_from_func 177"
value "multi_step tre0_ex1 gstk_transfer_from_func 178"
value "multi_step tre0_ex1 gstk_transfer_from_func 179"
value "multi_step tre0_ex1 gstk_transfer_from_func 180"
value "multi_step tre0_ex1 gstk_transfer_from_func 181"
value "multi_step tre0_ex1 gstk_transfer_from_func 182"
value "multi_step tre0_ex1 gstk_transfer_from_func 183"
value "multi_step tre0_ex1 gstk_transfer_from_func 184"
value "multi_step tre0_ex1 gstk_transfer_from_func 185"
value "multi_step tre0_ex1 gstk_transfer_from_func 186"
value "multi_step tre0_ex1 gstk_transfer_from_func 187"
value "multi_step tre0_ex1 gstk_transfer_from_func 188"
value "multi_step tre0_ex1 gstk_transfer_from_func 189"
value "multi_step tre0_ex1 gstk_transfer_from_func 190"
value "multi_step tre0_ex1 gstk_transfer_from_func 191"
value "multi_step tre0_ex1 gstk_transfer_from_func 192"
value "multi_step tre0_ex1 gstk_transfer_from_func 193"
value "multi_step tre0_ex1 gstk_transfer_from_func 194"
value "multi_step tre0_ex1 gstk_transfer_from_func 195"
value "multi_step tre0_ex1 gstk_transfer_from_func 196"
value "multi_step tre0_ex1 gstk_transfer_from_func 197"
value "multi_step tre0_ex1 gstk_transfer_from_func 198"
value "multi_step tre0_ex1 gstk_transfer_from_func 199"
value "multi_step tre0_ex1 gstk_transfer_from_func 200"
value "multi_step tre0_ex1 gstk_transfer_from_func 201"
value "multi_step tre0_ex1 gstk_transfer_from_func 202"
value "multi_step tre0_ex1 gstk_transfer_from_func 203"
value "multi_step tre0_ex1 gstk_transfer_from_func 204"
value "multi_step tre0_ex1 gstk_transfer_from_func 205"
value "multi_step tre0_ex1 gstk_transfer_from_func 206"
value "multi_step tre0_ex1 gstk_transfer_from_func 207"
value "multi_step tre0_ex1 gstk_transfer_from_func 208"
value "multi_step tre0_ex1 gstk_transfer_from_func 209"
value "multi_step tre0_ex1 gstk_transfer_from_func 210"
value "multi_step tre0_ex1 gstk_transfer_from_func 211"
value "multi_step tre0_ex1 gstk_transfer_from_func 212"
value "multi_step tre0_ex1 gstk_transfer_from_func 213"
value "multi_step tre0_ex1 gstk_transfer_from_func 214"
value "multi_step tre0_ex1 gstk_transfer_from_func 215"
value "multi_step tre0_ex1 gstk_transfer_from_func 216"
value "multi_step tre0_ex1 gstk_transfer_from_func 218"
value "multi_step tre0_ex1 gstk_transfer_from_func 219"
value "multi_step tre0_ex1 gstk_transfer_from_func 220"
value "multi_step tre0_ex1 gstk_transfer_from_func 221"
value "multi_step tre0_ex1 gstk_transfer_from_func 222"
value "multi_step tre0_ex1 gstk_transfer_from_func 224"
value "multi_step tre0_ex1 gstk_transfer_from_func 225"
value "multi_step tre0_ex1 gstk_transfer_from_func 226"
value "multi_step tre0_ex1 gstk_transfer_from_func 227"
value "multi_step tre0_ex1 gstk_transfer_from_func 228"
value "multi_step tre0_ex1 gstk_transfer_from_func 229"
value "multi_step tre0_ex1 gstk_transfer_from_func 230"
value "multi_step tre0_ex1 gstk_transfer_from_func 231"
value "multi_step tre0_ex1 gstk_transfer_from_func 232"
value "multi_step tre0_ex1 gstk_transfer_from_func 235"
value "multi_step tre0_ex1 gstk_transfer_from_func 236"
value "multi_step tre0_ex1 gstk_transfer_from_func 237"
value "multi_step tre0_ex1 gstk_transfer_from_func 238"
value "multi_step tre0_ex1 gstk_transfer_from_func 239"
value "multi_step tre0_ex1 gstk_transfer_from_func 240"
value "multi_step tre0_ex1 gstk_transfer_from_func 243"
value "multi_step tre0_ex1 gstk_transfer_from_func 244"
value "multi_step tre0_ex1 gstk_transfer_from_func 245"
value "multi_step tre0_ex1 gstk_transfer_from_func 246"
value "multi_step tre0_ex1 gstk_transfer_from_func 247"
value "multi_step tre0_ex1 gstk_transfer_from_func 248"
value "multi_step tre0_ex1 gstk_transfer_from_func 249"
value "multi_step tre0_ex1 gstk_transfer_from_func 250"
value "multi_step tre0_ex1 gstk_transfer_from_func 251"
value "multi_step tre0_ex1 gstk_transfer_from_func 252"
value "multi_step tre0_ex1 gstk_transfer_from_func 253"
value "multi_step tre0_ex1 gstk_transfer_from_func 254"
value "multi_step tre0_ex1 gstk_transfer_from_func 255"
value "multi_step tre0_ex1 gstk_transfer_from_func 256"
value "multi_step tre0_ex1 gstk_transfer_from_func 257"
value "multi_step tre0_ex1 gstk_transfer_from_func 261"
value "multi_step tre0_ex1 gstk_transfer_from_func 262"
value "multi_step tre0_ex1 gstk_transfer_from_func 263"
value "multi_step tre0_ex1 gstk_transfer_from_func 264"
value "multi_step tre0_ex1 gstk_transfer_from_func 265"
value "multi_step tre0_ex1 gstk_transfer_from_func 266"
value "multi_step tre0_ex1 gstk_transfer_from_func 267"
value "multi_step tre0_ex1 gstk_transfer_from_func 268"
value "multi_step tre0_ex1 gstk_transfer_from_func 269"
value "multi_step tre0_ex1 gstk_transfer_from_func 270"
value "multi_step tre0_ex1 gstk_transfer_from_func 271"
value "multi_step tre0_ex1 gstk_transfer_from_func 273"
value "multi_step tre0_ex1 gstk_transfer_from_func 274"
value "multi_step tre0_ex1 gstk_transfer_from_func 275"
value "multi_step tre0_ex1 gstk_transfer_from_func 276"
value "multi_step tre0_ex1 gstk_transfer_from_func 277"
value "multi_step tre0_ex1 gstk_transfer_from_func 278"
value "multi_step tre0_ex1 gstk_transfer_from_func 279"
value "multi_step tre0_ex1 gstk_transfer_from_func 280"
value "multi_step tre0_ex1 gstk_transfer_from_func 281"
value "multi_step tre0_ex1 gstk_transfer_from_func 282"
value "multi_step tre0_ex1 gstk_transfer_from_func 283"
value "multi_step tre0_ex1 gstk_transfer_from_func 284"
value "multi_step tre0_ex1 gstk_transfer_from_func 285"
value "multi_step tre0_ex1 gstk_transfer_from_func 286"
value "multi_step tre0_ex1 gstk_transfer_from_func 287"
value "multi_step tre0_ex1 gstk_transfer_from_func 288"
value "multi_step tre0_ex1 gstk_transfer_from_func 289"
value "multi_step tre0_ex1 gstk_transfer_from_func 290"
value "multi_step tre0_ex1 gstk_transfer_from_func 291"
value "multi_step tre0_ex1 gstk_transfer_from_func 292"
value "multi_step tre0_ex1 gstk_transfer_from_func 293"
value "multi_step tre0_ex1 gstk_transfer_from_func 294"
value "multi_step tre0_ex1 gstk_transfer_from_func 295"
value "multi_step tre0_ex1 gstk_transfer_from_func 296"
value "multi_step tre0_ex1 gstk_transfer_from_func 297"
value "multi_step tre0_ex1 gstk_transfer_from_func 298"
value "multi_step tre0_ex1 gstk_transfer_from_func 299"
value "multi_step tre0_ex1 gstk_transfer_from_func 300"
value "multi_step tre0_ex1 gstk_transfer_from_func 301"
value "multi_step tre0_ex1 gstk_transfer_from_func 302"
value "multi_step tre0_ex1 gstk_transfer_from_func 303"
value "multi_step tre0_ex1 gstk_transfer_from_func 304"
value "multi_step tre0_ex1 gstk_transfer_from_func 305"
value "multi_step tre0_ex1 gstk_transfer_from_func 306"
value "multi_step tre0_ex1 gstk_transfer_from_func 307"
value "multi_step tre0_ex1 gstk_transfer_from_func 308"
value "multi_step tre0_ex1 gstk_transfer_from_func 309"
value "multi_step tre0_ex1 gstk_transfer_from_func 310"
value "multi_step tre0_ex1 gstk_transfer_from_func 311"
value "multi_step tre0_ex1 gstk_transfer_from_func 312"
value "multi_step tre0_ex1 gstk_transfer_from_func 313"
value "multi_step tre0_ex1 gstk_transfer_from_func 314"
value "multi_step tre0_ex1 gstk_transfer_from_func 315"
value "multi_step tre0_ex1 gstk_transfer_from_func 316"
value "multi_step tre0_ex1 gstk_transfer_from_func 317"
value "multi_step tre0_ex1 gstk_transfer_from_func 318"
value "multi_step tre0_ex1 gstk_transfer_from_func 319"
value "multi_step tre0_ex1 gstk_transfer_from_func 320"
value "multi_step tre0_ex1 gstk_transfer_from_func 321"
value "multi_step tre0_ex1 gstk_transfer_from_func 322"
value "multi_step tre0_ex1 gstk_transfer_from_func 323"
value "multi_step tre0_ex1 gstk_transfer_from_func 324"
value "multi_step tre0_ex1 gstk_transfer_from_func 325"
value "multi_step tre0_ex1 gstk_transfer_from_func 326"
value "multi_step tre0_ex1 gstk_transfer_from_func 327"
value "multi_step tre0_ex1 gstk_transfer_from_func 328"
value "multi_step tre0_ex1 gstk_transfer_from_func 329"
value "multi_step tre0_ex1 gstk_transfer_from_func 330"
value "multi_step tre0_ex1 gstk_transfer_from_func 331"
value "multi_step tre0_ex1 gstk_transfer_from_func 332"
value "multi_step tre0_ex1 gstk_transfer_from_func 333"
value "multi_step tre0_ex1 gstk_transfer_from_func 334"
value "multi_step tre0_ex1 gstk_transfer_from_func 335"
value "multi_step tre0_ex1 gstk_transfer_from_func 336"
*)
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_from_func 300) 
          (get_allowance_offset (saddr_of gs1_bfun) 
            0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_from_func 301) 
          (get_allowance_offset (saddr_of gs1_bfun) 
            0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)"

value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_from_func 155) 
          (get_balance_offset 0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_from_func 156) 
          (get_balance_offset 0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c)"

value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_from_func 235) 
          (get_balance_offset 0x1234)"
value "get_val_from_storage 
          (multi_step tre0_ex1 gstk_transfer_from_func 236) 
          (get_balance_offset 0x1234)"

value "check_gs_gas_stp 
        (multi_step tre0_ex1 gstk_transfer_from_func 336) (3000000-18221)"

end